// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
  apiUrl: 'https://localhost:5001',
  sessionKey: {
    credentials : 'credentials'
  },
  userApi: {
    get: '/api/user/',
    login: '/api/user/authenticate',
    logout: '/api/user/logout',
    projectsSummary: '/api/user/userProjectsSummary'
  },
  postApi:{
    postByUser: 'post/GetByUser?id=',
    postByTag: 'post/GetByTag?id='
  },
  projectApi: {
    get: '/api/project/',
    getList: '/api/project/getList',
    getProjectPieces: 'api/project/pieces/',
    create: '/api/project/',
    update: '/api/project/'
  },
  pieceApi: {
    get: '/api/piece/',
    create: '/api/piece/',
    update: '/api/piece/'
  }
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
