// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
  apiUrl: 'https://localhost:5001',
  sessionKey: {
    credentials: 'credentials'
  },
  userApi: {
    get: '/api/user/',
    login: '/api/user/authenticate',
    logout: '/api/user/logout',
    projectsSummary: '/api/user/GetUserProjectsSummary'
  },
  postApi: {
    postByUser: 'post/GetByUser?id=',
    postByTag: 'post/GetByTag?id='
  },
  projectApi: {
    get: '/api/project/',
    getList: '/api/project/getList',
    getProjectPieces: 'api/project/pieces/',
    create: '/api/project/',
    update: '/api/project/'
  },
  pieceApi: {
    get: '/api/piece/',
    create: '/api/piece/',
    update: '/api/piece/'
  }
};
