// `.env.ts` is generated by the `npm run env` command
// apiUrl: 'https://www.projectr.live'
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  apiUrl: 'https://projectr.live',
  deployUrl: 'https://localhost:4200',
  sessionKey: {
    credentials: 'credentials'
  },
  userApi: {
    get: '/api/user/',
    login: '/api/user/authenticate',
    logout: '/api/user/logout',
    projectsSummary: '/api/user/GetUserProjectsSummary'
  },
  postApi: {
    postByUser: '/api/post/GetByUser?id=',
    postByTag: '/api/post/GetByTag?id='
  },
  projectApi: {
    get: '/api/project/getProjectById',
    getList: '/api/project/getPiecesListById',
    getProjectPieces: '/api/project/pieces/',
    create: '/api/project/',
    update: '/api/project/'
  },
  pieceApi: {
    get: '/api/projectpiece/',
    getList: '/api/projectpiece/getPiecesListById',
    create: '/api/projectpiece/',
    update: '/api/projectpiece/'
  }
};
